### PR TITLE
Add an io.Writer to splunk

### PR DESCRIPTION
**Pull request by mchaynes**
Decided that actually implementing logrus.Hook probably isn't the best way to go. Instead, just make an asynchronous io.Writer() that can be used for logging if wanted, or whatever else might be wanted

This allows us to use splunk as an output source in a much more flexible way
in particular, it allows us to be non blocking for uploading to splunk

Fixes: #6

### CODE REVIEW

**Comment by mchaynes** [comment]
Any chance you could take a look at this? @ZachtimusPrime

**Comment by ZachtimusPrime** [comment]
I'll take a look this morning! Sorry it's taken some time, I've had a real
hectic week.

**Comment by ZachtimusPrime** [comment]
Looks nice! I appreciate the thought put in with this over implementing a direct logrus hook. Would you mind adding some documentation to the readme at the root of the project for your additions before I merge?

**Comment by mchaynes** [comment]
Hey no rush, it's really not a priority.

**Comment by mchaynes** [comment]
Sure thing, I'll probably get that to you Monday realistically. Thanks for taking a look.

**Comment by mchaynes** [comment]
@ZachtimusPrime, updated readme

**Pull request merged**
