### PR TITLE
v2 is not backwards compatible

### PR DESCRIPTION
**Pull request by CodyDWJones**
Solves #17.

A Go module should be backwards compatible with all versions sharing its import path.  This was broken recently with the v2.0.0 tag.

The code was moved into a v2 directory so everyone will import the same path, whether they are using GOPATH or Go Modules:

`import "github.com/ZachtimusPrime/Go-Splunk-HTTP/splunk/v2"`

### CODE REVIEW

**Comment by CodyDWJones** [comment]
I *think* this will work...

**Comment by antoineco** [comment]
@CodyDWJones @ZachtimusPrime yes, that works. 👍

After this gets merged, all we need is a `v2.0.1` release to be able to use that version with Go modules.

**Review by antoineco — APPROVED** [review]

**Review by antoineco — COMMENTED** [review]
Travis is failing, you also need to add `/v2` to that line: https://github.com/ZachtimusPrime/Go-Splunk-HTTP/blob/b298e35fa1740ac47403576a5436b0921d0677f6/.travis.yml#L23

**Comment by antoineco** [comment]
@CodyDWJones it's not even for safety reason. Re-releasing v2.0.0 won't even work because Google controls https://proxy.golang.org/, and when a revision gets cached there, it remains there forever. I've run into this once already, and this is by design.

Long story short, a new release is the only option,

**Comment by ZachtimusPrime** [comment]
Alright, let's merge this then and get v2.0.1 up and running

**Pull request merged**
